language: python
cache:
- pip
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
script:
- python setup.py sdist
deploy:
  provider: pypi
  user: tisaconundrum
  password:
    secure: qexFrWlYa5JaiQYrTrNxsp8cyM9A1YOeiTaQmMPC5L8eTdlFlViLvvOR1cMg0iOqu3XJpgwC9kt4H6wqGDk4LINYMavScG+TSBng78Fo7G2P1MF1ezl9hPCbbJEMIBoQIyubfxQTvg0deL5zcur1CeYxSY3PudOckylPxGfyzAwJirrLZrUEpx3mKsu983t48mvXnUMFmIqjs3+u2QZSR0LyHlUB5rS8rSnmc9vZ/23b2ifhUd7P7QI94BwoGNK+yMyKfys7YJQuDiFKQJqhU8gbkSse0i+LA0M7SxTcWqhCwlTAgAidXucwUFvedZmqEl0SfZ56vxsDzwxfbo+PdLixKSQaCBhiPWKjycbxn5pFtHTcC7GUdiQ9uDYVSxUDdKQzMYufGI0M7jclmPsvyr+x1ku4aTsBrkfFGM7INzZWKgMSuu1ZiaUkTJRO6ZbW6Nr2a5aH4LWfYn3vz2DsyziC3+brFCrSbgBFRn35klNNHGe0O9BLvGb81BIrWNRWhLXTEK+X38DpXvNMSIdiD4fgB6irEwJsawIZa6VODT39TbjOuYuOf+wX7Noid/gWUECQwxc7Aug3wI5i53KO0O5FNBWepj/lQtIerGLA2PLEp+FQphULkbDdQBDDA+wkBgfespY4z38Wkt7u4EvrPv/RBtDrh+dcgCnA2a45vTY=
  on:
    branch: master

